my_string = input("Введите строку: ")
print(f"Длина строки: {len(my_string)}")
print("Строка в верхнем регистре:\n", my_string.upper())
print("Строка в нижнем регистре:\n", my_string.lower())
print("Строка без пробелов:\n", my_string.replace(" ", ""))
print("Первый символ строки: ", my_string[0])
print("Последний символ строки: ", my_string[-1])